src/SimpleWebShop/Web/SimpleWebShop.Web/Areas/Administration/Controllers/ProductsAdministrationController.cs
using System.Linq;
using System.Web.Mvc;
using SimpleWebShop.Services.Data.Contracts;
using SimpleWebShop.Web.Areas.Administration.Services;
using SimpleWebShop.Web.Areas.Administration.ViewModels;
using SimpleWebShop.Web.Controllers;

namespace SimpleWebShop.Web.Areas.Administration.Controllers
{
    public class ProductsAdministrationController : AdministrationBaseController
    {
        private readonly ICategoriesServices categoriesServices;
        private readonly IAdminProductsServices adminProductsServices;

        public ProductsAdministrationController(
            ICategoriesServices categoriesServices, 
            IAdminProductsServices adminProductsServices
        )
        {
            this.categoriesServices = categoriesServices;
            this.adminProductsServices = adminProductsServices;
        }
        // GET: Administration/ProductsAdministration
        public ActionResult Create()
        {
            var viewModel = new CreateProductInputModel()
            {
                AllCategoriesNames = this.categoriesServices.GetAllCategoriesNames()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateProductInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(inputModel);
            }
            this.adminProductsServices.CreateProduct(inputModel);
            return this.RedirectToAction("ProductsControlPanel", "Dashboard");
        }
    }
}

src/SimpleWebShop/Web/SimpleWebShop.Web/Areas/Administration/Views/ProductsAdministration/Create.cshtml
@model SimpleWebShop.Web.Areas.Administration.ViewModels.CreateProductInputModel
@{
    ViewBag.Title = "Index";
}

<h1>Create Product</h1>
<div class="col-md-10">
    @using (Html.BeginForm("Create", "ProductsAdministration", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div>
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = nameof(Model.Name) })
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div>
            @Html.LabelFor(x => x.Price)
            @Html.TextBoxFor(x => x.Price, new { @class = "form-control", placeholder = nameof(Model.Price) })
            @Html.ValidationMessageFor(x => x.Price)
        </div>
        <div>
            @Html.LabelFor(x => x.Description)
            @Html.TextBoxFor(x => x.Description, new { @class = "form-control", placeholder = nameof(Model.Description) })
            @Html.ValidationMessageFor(x => x.Description)
        </div>
        <div>
            @Html.LabelFor(x => x.Color)
            @Html.TextBoxFor(x => x.Color, new { @class = "form-control", placeholder = nameof(Model.Color) })
            @Html.ValidationMessageFor(x => x.Color)
        </div>
        <div>
            @Html.LabelFor(x => x.Weight)
            @Html.TextBoxFor(x => x.Weight, new { @class = "form-control", placeholder = nameof(Model.Weight) })
            @Html.ValidationMessageFor(x => x.Weight)
        </div>
        <div>
            @Html.LabelFor(x => x.Size)
            @Html.TextBoxFor(x => x.Size, new { @class = "form-control", placeholder = nameof(Model.Size) })
            @Html.ValidationMessageFor(x => x.Size)
        </div>
        <div>
            @Html.LabelFor(x => x.ProductsOnStock)
            @Html.TextBoxFor(x => x.ProductsOnStock, new { @class = "form-control", placeholder = nameof(Model.Description) })
            @Html.ValidationMessageFor(x => x.ProductsOnStock)
        </div>
        <div>
            @Html.LabelFor(x => x.ProductCategoryName)
            @Html.DropDownList(nameof(Model.ProductCategoryName),
                new SelectList(Model.AllCategoriesNames),
                new { @class = "form-control" })
        </div>
        <div class="row justify-content-center mt-3">
            <button type="submit" class="btn btn-success">Create</button>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}