src/SimpleWebShop/Web/SimpleWebShop.Web/Areas/Administration/Controllers/DashboardController.cs
using System.Web.Mvc;
using SimpleWebShop.Services.Data.Contracts;
using SimpleWebShop.Web.Areas.Administration.ViewModels;
using SimpleWebShop.Web.Controllers;

namespace SimpleWebShop.Web.Areas.Administration.Controllers
{
    public class DashboardController : AdministrationBaseController
    {
        private readonly IProductsControlPanelServices productsControlPanelServices;

        public DashboardController(IProductsControlPanelServices productsControlPanelServices)
        {
            this.productsControlPanelServices = productsControlPanelServices;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductsControlPanel()
        {
            return this.View();
        }
    }
}

src/SimpleWebShop/Web/SimpleWebShop.Web/Controllers/CategoriesController.cs
using System.Web.Mvc;
using SimpleWebShop.Services.Data.Contracts;

namespace SimpleWebShop.Web.Controllers
{
    public class CategoriesController : BaseController
    {
        private readonly ICategoriesServices categoriesServices;

        public CategoriesController(ICategoriesServices categoriesServices)
        {
            this.categoriesServices = categoriesServices;
        }
        public ActionResult Index(string category, string admin)
        {
            ViewData["category"] = category;
            var viewModel = this.categoriesServices.GetCategoryViewModel(category);
            if (this.User.IsInRole("Administrator") && !string.IsNullOrEmpty(admin) && admin == "True")
            {
                return this.View("AdminIndex", viewModel);
            }
            //TODO: Finish show info if an admin(Edit, Delete, ...) is watching otherwise show info for normal customer
            //TODO: If the category has child categories list them otherwise list the products

            return this.View(viewModel);
        }   
    }
}

src/SimpleWebShop/Web/SimpleWebShop.Web/Views/Shared/LayoutPartials/_FooterPartial.cshtml
<footer class="page-footer font-small special-color-dark pt-4" id="footer">
    <!-- Footer Elements -->
    <div class="container">
        <!-- Social buttons -->
        <ul class="list-unstyled list-inline text-center social-network-contacts">
            <li class="list-inline-item">
                <a class="btn-floating btn-fb mx-1">
                    <i class="fab fa-facebook-f"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-tw mx-1">
                    <i class="fab fa-twitter"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-gplus mx-1">
                    <i class="fab fa-google-plus-g"> </i>
                </a>
            </li>
        </ul>
        <!-- Social buttons -->

    </div>
    <!-- Footer Elements -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-2">
        © 2019 - @(DateTime.UtcNow.Year + 1) Copyright:
        <a href="https://github.com/svetlimladenov/SimpleWebShop">SimpleWebShop</a>
    </div>
    <!-- Copyright -->

</footer>

src/SimpleWebShop/Web/SimpleWebShop.Web/Views/Shared/LayoutPartials/_NavPartial.cshtml
@using SimpleWebShop.Web.Infrastructure.Extensions
<div class="nav-wrapper">
    <nav class="mb-1 navbar navbar-expand-md navbar-dark unique-color-dark body-container" id="header">
        @Html.ActionLink("SimpleWebShop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
                aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="dropdown categoriesNav">
            <button class="btn text-white dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: 200px">
                <div class="main-menu" id="main-menu-nav">
                    @*load via ajax*@
                </div>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
            <ul class="navbar-nav mr-auto">
                <form class="form-inline">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    </div>
                </form>
            </ul>
            @if (this.User.Identity.IsAuthenticated)
            {
                <ul class="navbar-nav ml-auto nav-flex-icons">
                    <li class="nav-item">
                        <a class="nav-link waves-effect waves-light">
                            <i class="fas fa-shopping-cart"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-default"
                             aria-labelledby="navbarDropdownMenuLink-333">
                            @if (this.User.IsInRole("Administrator"))
                            {
                                @Html.ActionLink("Administration", "Index", "Dashboard", new { area = "Administration" }, new { @class = "dropdown-item" })
                            }

                            @Html.ActionLink("My Profile", "Index", "Manage", new { area = "" }, new { @class = "dropdown-item" })

                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                            {
                                @Html.AntiForgeryToken()
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="dropdown-item">Log off</a>
                            }

                        </div>
                    </li>
                </ul>
            }
            else
            {
                <ul class="navbar-nav ml-auto nav-flex-icons">
                    <li class="nav-item">
                        @Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            }
        </div>
    </nav>
</div>

src/SimpleWebShop/Web/SimpleWebShop.Web/Views/Shared/LayoutPartials/_SideBarCategories.cshtml
@model ICollection<SimpleWebShop.Services.Models.ViewModels.Categories.SingleCategoryViewModel>
@*<nav class="navbar navbar-expand-sm navbar-dark unique-color-dark main-menu">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav" style="flex-direction: column" id="sidebarCategories">
                @foreach (var category in Model)
                {
                    <li class="nav-item"><a class="nav-link" href="/@category.NameForLink"><i class="fas fa-@category.IconClass"></i> @category.Name </a></li>
                }
            </ul>
        </div>
        <div class="drop-down">
            <h3 class="drop-down-title text-center">Category name</h3>
        </div>
    </nav>*@

<div class="main-menu">
    @foreach (var category in Model)
    {
        <div class="btn-group dropright dropdown">
            <button type="button" class="btn text-left dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-@category.IconClass"></i> @category.Name
            </button>
            <div class="dropdown-menu">
                <h4 class="child-category-header">@category.Name</h4>
                @foreach (var child in category.ChildCategories)
                {
                    @Html.ActionLink(child.Name, "Index", "Categories", new {category = child.NameForLink}, new {@class = "dropdown-item"})
                }
            </div>
        </div>
    }
</div>